import type { Metadata } from "next";
import { Nunito, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ExitMoDal } from "@/components/modals/exit-modal";

const font = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
      >
        <body className={font.className}>
          <Toaster />
            <ExitMoDal />
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
